### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by apeream** [SPL-201620/RCBike#1]
![casosusorcbike](https://cloud.githubusercontent.com/assets/20938243/17650475/b08c31b0-6214-11e6-9859-473f639bdeb7.png)

**Comment by ghost** [comment]
Esta es mi propuesta del diagrama:
- Cambie "Consultar ruta" por "Buscar recorrido", me parecía confuso la palabra consultar, es como si ya existiera la información
- Agregué lo que se mencionaba en el enunciado de compartir los recorridos en Facebook y Twitter
- Cambie "Alquilar bicicleta" por "Buscar Alquiler de bicicleta", ya que realmente no las alquilamos solo buscamos donde
- Modifiqué el nombre a "Generar reporte de actividad" para hacerlo mas especifico

![casos de uso](https://cloud.githubusercontent.com/assets/101752/17655783/cd389fd4-6277-11e6-87cb-8be4ccbd484b.png)

**Comment by juanca0517** [comment]
Buenos días, me parece que lo propuesto esta bien, solo agregue lo que se enuncia en el ejercicio como unirse al recorrido, el cual dependerá de la consulta de los recorridos.

![casosdeuso](https://github.com/SPL-201620/RCBike/raw/archivos/Casos%20de%20Uso.png)

**Comment by apeream** [comment]
Agregué caso de uso "Vender bicicleta" para completar requerimiento con opción seleccionada por el profesor
![usecasesv3](https://cloud.githubusercontent.com/assets/20938243/17782313/81153630-6538-11e6-8b44-e6b90b1d9f4e.jpg)

**Comment by ghost** [comment]
Agregué los casos de uso para la funcionalidad de venta, el archivo se encuentra en el Drive

![casosusorcbike](https://cloud.githubusercontent.com/assets/101752/17872345/3d37f510-6885-11e6-9bff-8520a6c5cc4f.png)

**Comment by apeream** [comment]
![casosuso](https://cloud.githubusercontent.com/assets/20938243/18070826/35edcef6-6e16-11e6-9830-a3d1614cb848.png)
