### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by apeream** [SPL-201620/RCBike#2]
![diagramaclasesrcbike](https://cloud.githubusercontent.com/assets/20938243/17650484/c7526af4-6214-11e6-8372-407cc66abf73.png)

**Comment by armandoperea** [comment]
![diagramaclasesrcbike](https://cloud.githubusercontent.com/assets/20938243/17683789/b3bbbb28-631b-11e6-9ed4-b5776e7c2c88.png)

**Comment by apeream** [comment]
Subo versión 2 de diagrama de clases que fue entregada
![classesv2](https://cloud.githubusercontent.com/assets/20938243/17782445/1b534764-6539-11e6-8a03-8f7544821f97.png)

**Comment by apeream** [comment]
- Agregué clase "VentaBicicleta" y "PreguntaCompra" para el soporte del caso de uso "Venta Bicicleta". “VentaBicicleta” es una especialización de “BicicletaConfigurada” que tiene un comprador que es un “Usuario”. Una “VentaBicicleta” puede tener varias preguntas que tienen una persona que pregunta (Interrogador)
- Agregué identificadores a varias clases que, aunque se supone se generan, aquí se evidencian
- Agregué multiplicidad infinita a relación “RutaOrganizada” – “Usuario” para relación con rol “participante” lo que la convierte en una relación muchos a muchos y por tanto se generará una clase de relación
- Agregué enumeración “TipoRuta” y atributo “tipoRuta” a clase “RutaRealizada” para soportar el reporte
- Agregué relación “Ruta” – “Usuario” para dar acceso a las rutas recién creadas pero no realizadas
- Agregué atributo “fechaHora” a “Mensaje” para poder presentarlos de forma organizada
- Agregué clase “ModuloInstalado” y enumeración ”ModuloInstalacion” para el control del uso de las interfaces de componentes instalados
- Agregué clases utilitarias para parámetros y autenticación en redes sociales

![classmodelv3](https://cloud.githubusercontent.com/assets/20938243/17757699/80e6f728-64ae-11e6-98f4-1ea234515e3e.jpg)

**Comment by ghost** [comment]
Entrega semana 3
![clases](https://cloud.githubusercontent.com/assets/101752/17877799/a3213582-68ab-11e6-88e3-e75ef95e83a3.png)

**Comment by apeream** [comment]
![clases](https://cloud.githubusercontent.com/assets/20938243/18070808/1427bea8-6e16-11e6-937b-ad824815b08a.png)
