### ISSUE TITLE
Propuestas de valor

### ISSUE THREAD

**Issue by ghost** [SPL-201620/RCBike#3]
Voy a agregar aca las propuestas que se escribieron el home

**Comment by ghost** [comment]
### Domicilios [AUTOR?]

Pide tu bicicleta desde cualquier parte de la ciudad y nosotros te la hacemos llegar

**Comment by ghost** [comment]
### Partners internacionales (Roaming) [AUTOR?]

Usa la bicicleta como transporte en ciudades como New York, París, etc. con nuestros socios internacionales

**Comment by juanca0517** [comment]
### Cycle parking

Buenos días, como propuesta y para discusión,  

Ubicación de cicloparqueaderos cerca a tu lugar de destino. Luego de seleccionar su destino y ruta a seguir, el usuario contara con una lista de cicloparquederos ubicados cerca del sitio de llegada, de los cuales podrá obtener información básica, como ubicación, costo, y referencias.

**Comment by juanca0517** [comment]
### Free bicycle

El usuario podrá consultar los establecimientos públicos o privados que se encuentren cerca a su ubicación y que cuenten con el servicio de préstamo o alquiler de bicicletas, al elegir una de las opciones podrá consultar las condiciones, características del préstamo de estas y disponibilidad de las mismas.

**Comment by raulgomezn** [comment]
### Propuesta de valor

Viaja con los amigos de la universidad o ve donde hay un grupo para salir, obten información del clima y las calorias que has quemado todo desde tu teléfono celular o Computador.
- Componente (Sitio Responsive)

### Relaciones con clientes

...

### Canales
- Redes sociales de la universidad (SEO, SEM)

### Segmento de clientes

Usuario de la Universidad  de los Andes que frecuentemente usan bicicleta para ir ya sea a trabajar o al estudio.

### Socios Claves
- Universidad de los Andes
- Biciparqueaderos
- Tiendas de bicicletas
- Alcaldía de Bogotá

### Recursos claves
- Servidores en la nube
- Equipos de computo

### Estructura de costos
- Pago de servidores

### Fuente de ingresos
- Publicidad*

**Comment by ghost** [comment]
## Venta de Bicicletas

Un usuario puede publicar su bicicleta para la venta agregando un foto del producto, características, partes (podemos usar las misma información de partes con la que se configura una bicicleta), precio y ubicacion geografica del producto. Otros usuarios podran buscar bicicletas a la venta y comprar las ofertas presentes

**Comment by ghost** [comment]
La propuesta de Cycle parking, me gustó, yo tambien la pense pero cuando busque en google solo retorna tres puntos como sitios de biciparqueaderos.... entonces no se que tan util terminara siendo y pues ponerse a levantar información como que no
