### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by apeream** [SPL-201620/RCBike#4]
![componentmodelv1](https://cloud.githubusercontent.com/assets/20938243/17757706/937b3ea8-64ae-11e6-9c3d-7cde54e6358d.jpg)

**Comment by apeream** [comment]
![componentmodelv2](https://cloud.githubusercontent.com/assets/20938243/17779002/b64d0f4c-652b-11e6-8f20-9b94a20189aa.jpg)

**Comment by ghost** [comment]
![diagrama de componentes](https://cloud.githubusercontent.com/assets/101752/17878134/509f4b7a-68ae-11e6-88ee-6e70bfa093e8.png)

**Comment by ghost** [comment]
![interfaces](https://cloud.githubusercontent.com/assets/101752/17878260/3de71444-68af-11e6-9963-552d5493f3f7.png)

**Comment by apeream** [comment]
![componentes](https://cloud.githubusercontent.com/assets/20938243/18070771/cc524ce2-6e15-11e6-96a4-70cb5a49db47.png)
![interfaces](https://cloud.githubusercontent.com/assets/20938243/18070785/e4d2ff78-6e15-11e6-82cd-c5ce98ba400e.png)
