### ISSUE TITLE
Diagrama de Despliegue

### ISSUE THREAD

**Issue by raulgomezn** [SPL-201620/RCBike#5]
Este diagrama esta inspirado en la arquitectura que me mencionó Felipe.
![diagramadedespliegue](https://cloud.githubusercontent.com/assets/1523315/17841372/5fb6e644-67dd-11e6-8b86-d7c0927e7430.png)

**Comment by ghost** [comment]
Le agregué detalle al diagrama de Raul, el archivo original esta en el Drive
![diagramadedespliegue](https://cloud.githubusercontent.com/assets/101752/17877225/0cbec676-68a7-11e6-968f-a2ae2e91277d.png)

**Comment by raulgomezn** [comment]
Aqui!!

**Comment by juanca0517** [comment]
![diagramadedesplieguercbike](https://cloud.githubusercontent.com/assets/20893924/17878393/f8641f4c-68af-11e6-8444-c62eba8cddb3.png)
Publicación 22/08/2016

**Comment by apeream** [comment]
![despliegue](https://cloud.githubusercontent.com/assets/20938243/18070747/9104810a-6e15-11e6-94fb-4e48a25decce.png)
